# Generated by Django 5.2.6 on 2025-09-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grade',
            new_name='academic_level',
        ),
    ]
