# Generated by Django 5.2.6 on 2025-09-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_grade_user_academic_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='student',
        ),
    ]
