# Generated by Django 5.2.6 on 2025-10-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_date_of_birth_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutional_id', models.CharField(help_text='Unique institutional ID (e.g., student ID, employee ID)', max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff/Faculty')], help_text='Type of account this ID is authorized for', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', help_text='Current status of this institutional ID', max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('academic_level', models.CharField(blank=True, choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior'), ('graduate', 'Graduate Student'), ('phd', 'PhD Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('admin', 'Administrator')], max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this ID', null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this ID was used for registration', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this ID', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_institutional_ids', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='User who registered with this ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institutional ID',
                'verbose_name_plural': 'Institutional IDs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='institutional_id',
            field=models.OneToOneField(blank=True, help_text='The institutional ID used during registration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.institutionalid'),
        ),
        migrations.AddIndex(
            model_name='institutionalid',
            index=models.Index(fields=['institutional_id'], name='accounts_in_institu_110632_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionalid',
            index=models.Index(fields=['status'], name='accounts_in_status_b322c4_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionalid',
            index=models.Index(fields=['account_type'], name='accounts_in_account_9af335_idx'),
        ),
    ]
