# Generated by Django 5.2.6 on 2025-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_institutionalid_user_institutional_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalid',
            name='institutional_id',
            field=models.CharField(blank=True, help_text='Unique institutional ID (e.g., student ID, employee ID). Leave blank to auto-generate.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, help_text='Faculty or staff member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=False, help_text='Student account'),
        ),
    ]
